# Format: 
# [redirects.subdomain]
# url = "target_url"
# description = "A short description"
# aliases = ["alias1", "alias2"]  # Optional: Additional subdomains that point to the same target

[redirects.mensa]
url = "https://www.studierendenwerk-aachen.de/de/Gastronomie/mensa-academica-wochenplan.html"
description = "Check today's menu at Mensa Academica"
aliases = ["hunger", "essen", "academica"]

[redirects.mail]
url = "https://mail.rwth-aachen.de"
description = "Access your RWTH email inbox"

[redirects.online]
url = "https://online.rwth-aachen.de"
description = "Visit RWTHonline"
aliases = ["o"]

[redirects.moodle]
url = "https://moodle.rwth-aachen.de"
description = "Access your course materials" 
aliases = ["m"]

[redirects.notenstreicher]
url = "https://notenstreicher.laurenzfg.com/"
description = "Informatik Abschluss Notenstreicher" 

[redirects.wo]
url = "https://www.rwth-aachen.de/go/id/cxcq"
description = "RWTH Gebäudesuche" 

[redirects.offline]
url = "https://rwthoffline.de/"
description = "RWTHoffline (more usable course overview)" 

[redirects.supra]
url = "https://supra.informatik.rwth-aachen.de"
description = "CS seminar and practical registration" 

[redirects.sc]
url = "https://sc.informatik.rwth-aachen.de"
description = "Studiencenter Informatik" 

[redirects.wlan]
url = "https://app.rwth-aachen.de/eduroam"
description = "Manage eduroam devices"
aliases = ["wifi", "eduroam", "roam"] 

[redirects.htwr]
url = "https://htwr-aachen.de"
description = "Collection of RWTH CS materials"
