# Format: 
# [redirects.subdomain]
# url = "target_url"
# description = "A short description"
# aliases = ["alias1", "alias2"]  # Optional: Additional subdomains that point to the same target

[redirects.mensa]
url = "https://www.studierendenwerk-aachen.de/de/Gastronomie/mensa-academica-wochenplan.html"
description = "Check today's menu at Mensa Academica"
aliases = ["hunger", "essen", "academica"]

[redirects.mail]
url = "https://mail.rwth-aachen.de"
description = "Access your email inbox"

[redirects.online]
url = "https://online.rwth-aachen.de"
description = "Visit RWTHonline"
aliases = ["o"]

[redirects.moodle]
url = "https://moodle.rwth-aachen.de"
description = "Access your course materials"
aliases = ["m"]

[redirects.streicher]
url = "https://notenstreicher.laurenzfg.com/"
description = "Informatik Abschluss Notenstreicher"
aliases = ["notenstreicher"]

[redirects.wo]
url = "https://www.rwth-aachen.de/go/id/cxcq"
description = "Gebäudesuche"

[redirects.offline]
url = "https://rwthoffline.de/"
description = "RWTHoffline (more usable course overview)"

[redirects.supra]
url = "https://supra.informatik.rwth-aachen.de"
description = "CS seminar and practical registration"

[redirects.sc]
url = "https://sc.informatik.rwth-aachen.de"
description = "Studiencenter Informatik"

[redirects.wlan]
url = "https://app.rwth-aachen.de/eduroam"
description = "Manage eduroam devices"
aliases = ["wifi", "eduroam", "roam"]

[redirects.htwr]
url = "https://htwr-aachen.de"
description = "Collection of CS materials"

[redirects.zpa]
url = "https://www.rwth-aachen.de/cms/root/studium/Im-Studium/Pruefungsangelegenheiten/~cbcn/Kontakte-im-ZPA-nach-Sachgebieten"
description = "ZPA Ansprechpersonen"

[redirects.rwtf]
url = "https://rwtf.dorianko.ch/"
description = "Gym Utilization (and more) by Dorian Koch"

[redirects.gymstats]
url = "https://gymstats.the-codeboy.com/"
description = "Gym Utilization by the-codeboy"

[redirects.gym-tracker]
url = "https://data-science-club.de/gym-tracker/"
description = "Gym tracker by Data Science Club"
aliases = ["gt"]

[redirects.gym]
url = "https://hochschulsport.rwth-aachen.de/cms/hsz/sport/sportangebot/fitnesstraining/~huqam/fitnesstrainingskarten/?lidx=1"
description = "Gym website"

[redirects.gymkarten]
url = "https://buchung.hsz.rwth-aachen.de/angebote/aktueller_zeitraum/_Fitnesstrainingskarten.html"
description = "Buy Gym membership"

[redirects.s-inf]
url = "http://s-inf.de/"
description = "Skriptesammlung Informatik"

[redirects.wahlpflicht]
url = "https://sc.informatik.rwth-aachen.de/de/wahlpflicht/"
description = "Current CS elective courses"
aliases = ["elective"]

[redirects.wptabelle]
url = "https://docs.google.com/spreadsheets/d/1oOVX-vhUPkz6hcY8otHVBr5wD80cAb8Nyp8YFY0vSpI/edit?gid=890111908#gid=890111908"
description = "Informatik Wahlpflichtmodule Google Sheet"

[redirects.sz]
url = "https://verwaltung.sz.rwth-aachen.de/st/"
description = "Language Center website"
aliases = ["sprachzentrum", "lang", "language", "lc"]

[redirects.upo]
url = "https://www.rwth-aachen.de/global/show_document.asp?id=aaaaaaaacsyawsi"
description = "Übergreifende Prüfungsordnung"

[redirects.regapp]
url = "https://regapp.itc.rwth-aachen.de/welcome/index.xhtml"
description = "HPC Cluster Registration & Benutzerkonto App"
aliases = ["hpc"]

[redirects.hpcdocs]
url = "https://help.itc.rwth-aachen.de/service/rhr4fjjutttf/"
description = "HPC Cluster Dokumentation"

[redirects.quit]
url = "https://www.rwth-aachen.de/global/show_document.asp?id=aaaaaaaaaaajyav&download=1"
description = "Aufgeben ist die letzte Option!"
alias = ["getmeoutofrwth", "aufgeben"]

[redirects.fsphil]
url = "https://www.fsphil.rwth-aachen.de"
description = "Website of the Humanities and Social Sciences Department (Geistes- und Gesellschaftswissenschaften)"

[redirects.sport]
url = "https://hochschulsport.rwth-aachen.de/cms/HSZ/Sport/~hpoua/Sportartensuche/"
description = "Sport program website"
aliases = [
  "hochschulsport",
  "sportangebot",
  "sportarten",
  "hs-sport",
  "hssport",
]

[redirects.video]
url = "https://video.fsmpi.rwth-aachen.de/"
description = "Lecture recordings website of the student council for math, physics, and computer science"
aliases = ["videoag", "video-ag", "recordings"]

[redirects.fsmpi]
url = "https://www.fsmpi.rwth-aachen.de/"
description = "Website of the student council for math, physics, and computer science"
aliases = ["maphin", "maphins"]

[redirects.selfservice]
url = "https://idm.rwth-aachen.de/selfservice"
description = "Configuration for your RWTH Identity (Token Manager, Passwords & more)"

[redirects.status]
url = "https://maintenance.itc.rwth-aachen.de/ticket/status/messages"
description = "RWTH maintenance information"

[redirects.kino]
url = "https://www.filmstudio.rwth-aachen.de"
description = "RWTH film studio"
aliases = ["film", "cinema"]

[redirects.chat]
url = "https://chat.kiconnect.nrw/"
description = "RWTHgpt"
aliases = ["gpt", "chatgpt"]

[redirects.ra]
url = "https://ra-portal.itc.rwth-aachen.de"
description = "Manage your RWTH certificates"
aliases = ["cert", "sign"]

[redirects.asta]
url = "https://asta.rwth-aachen.de"
description = "University-wide representative body for all students at RWTH"

[redirects.fsmb]
url = "https://fsmb.rwth-aachen.de"
description = "Student council for mechanical engineers"

[redirects.calendar]
url = "https://asta.ac/kalender"
description = "Calender with many events happening for students managed by asta"

[redirects.psycho-councel]
url = "https://www.rwth-aachen.de/go/id/sei"
description = "Psychological counseling by RWTH"
