# Format: 
# [redirects.subdomain]
# url = "target_url"
# description = "A short description"

[redirects.mensa]
url = "https://www.studierendenwerk-aachen.de/en/eating-drinking/mensa-academica-2.html"
description = "Check today's menu at Mensa Academica"

[redirects.mail]
url = "https://mail.rwth-aachen.de"
description = "Access your RWTH email inbox"

[redirects.campus]
url = "https://campus.rwth-aachen.de"
description = "Manage your studies and exams"

[redirects.moodle]
url = "https://moodle.rwth-aachen.de"
description = "Access your course materials" 
