---
name: Deploy Docker Compose on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd rwth.cool/
            git fetch origin
            git reset --hard origin/main
            docker compose pull
            docker compose up -d --build --force-recreate
            docker system prune -f

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
